[project]
name = "btsbots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "base58>=2.1.1",
    "bitshares>=0.7.1",
    "cryptography>=50.0.0",
    "pycryptodome>=3.23.0",
    "websockets>=17.0.1",
]

[tool.setuptools]
packages = ["btsbots"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
